import { BeersField } from './BeersField';

/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2021-05-16 10:34:07
 */
export interface IExpandedElementComponent {
  expansionData: BeersField;
}
