import { readFile, writeFileSync } from 'fs';
import { fetch } from 'cross-fetch';
let inFile = './beers-entries.json';
const brandURI = (cui: string): string =>
  `https://rxnav.nlm.nih.gov/REST/rxcui/${cui}/related.json?tty=bn`;

let writeContent = [];
export interface Drug {
  id: number;
  url: string;
  brands: { rxcui: string; name: string }[];
  classId: string;
}
export interface Generic {
  rxcui: string;
  generic: string;
  id: number;
  uri: string;
}
// Generated by https://quicktype.io

export interface Entry {
  EntryID: number;
  DiseaseState: string;
  Category: number;
  TableDefinition: string;
  Item: string;
  ClassID: string;
  LowerLimit: number;
  UpperLimit: number;
  DrugInteraction: string;
  Inclusion: string;
  Exclusion: string;
  Rationale: string;
  Recommendation: string;
  RecommendationLineTwo: string;
  ItemType: string;
  ShortTableName: string;
}

readFile(inFile, (err, data) => {
  let parsed = <Entry[]>JSON.parse(data.toString());
  for (let parse of parsed) {
    if (parse.ItemType === 'therapeutic category') {
    }
  }
});
