/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2021-05-16 10:34:07 
*/
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";
import { BeersField } from "../../../services/data.service";

export interface IExpandedElementComponent {
    expansionData: BeersField;
}
